version: "3.8"

services:
  pytorch:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pytorch_container
    ports:
      - "8888:8888"
    volumes:
      - .:/workspace
    gpus:
      - "all"                     # Changed to list syntax
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
