version: '3'
services:
  pytorch:
    image: nvcr.io/nvidia/pytorch:23.12-py3
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - .:/workspace
    ports:
      - "8888:8888"
    command: jupyter lab --ip=0.0.0.0 --port=8888 --allow-root --no-browser --NotebookApp.token='' --NotebookApp.password=''
    network_mode: host