version: '3'
services:
  dev:
    build: .
    image: pytorch-dev
    container_name: pytorch-dev
    volumes:
      - .:/workspace
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - "8888:8888"  # For JupyterLab
    tty: true
    stdin_open: true